#!/bin/bash
script_dir=`dirname $0`
cd $script_dir

if [ ! -d "venv" ]; then
    sudo pip install virtualenv
    virtualenv -p python3.5 venv
fi

source "venv/bin/activate"

cd src/
python3 setup.py develop